CREATE TABLE users (
                       id VARCHAR(255) PRIMARY KEY,
                       login VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL
);

CREATE TABLE tb_produtos (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome VARCHAR(255) NOT NULL,
                             codigo_barras VARCHAR(255),
                             preco NUMERIC(19, 2) NOT NULL
);

CREATE TABLE tb_estoque (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            quantidade INTEGER NOT NULL,
                            produto_id BIGINT UNIQUE,
                            CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id) REFERENCES tb_produtos(id)
);