CREATE TABLE tb_categories (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(255) NOT NULL UNIQUE,
                               parent_id BIGINT,
                               CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES tb_categories(id)
);

ALTER TABLE tb_produtos ADD COLUMN category_id BIGINT;

ALTER TABLE tb_produtos ADD CONSTRAINT fk_produto_category FOREIGN KEY (category_id) REFERENCES tb_categories(id);