CREATE TABLE tb_inventory_transactions (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   product_id BIGINT NOT NULL,
   quantity INTEGER NOT NULL,
   reason VARCHAR(50) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_transaction_product FOREIGN KEY (product_id) REFERENCES tb_produtos(id)
);