CREATE TABLE tb_carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL, -- Relacionamento com a tabela users (que usa UUID string)
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE tb_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price_snapshot NUMERIC(19, 2) NOT NULL, -- O preço no momento da adição
    CONSTRAINT fk_item_cart FOREIGN KEY (cart_id) REFERENCES tb_carts(id),
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES tb_produtos(id)
);