CREATE TABLE tb_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    total NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL, -- CREATED, PAID, SHIPPED...
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE tb_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price NUMERIC(19, 2) NOT NULL, -- Preço final pago
    CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id) REFERENCES tb_orders(id),
    CONSTRAINT fk_orderitem_product FOREIGN KEY (product_id) REFERENCES tb_produtos(id)
);